name: first workflow

on:
  push:
    branches:
      - main 

jobs:
  example-jop:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome 
        run: echo  "welcome"

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: list repos
        run: ls -la
